#!/usr/bin/env ruby

# Javier Lopez 11-10552
# Patricia Reinoso 11-10851

require_relative './lexer/findRegex'
require_relative './parser/racc.rb'

def main
    myfile = File::read(ARGV[0])
    if ARGV.length == 1
        lexer  = FindRegex::new(myfile)
        lexer.findAll

        if lexer.errorFound
            lexer.printOutPut
        else
            parser = Calcparser::Parser.new.parser(lexer.toList)
            parser.print
        end

        
    end
end

main