#!/usr/bin/env ruby

# Javier Lopez 11-10552
# Patricia Reinoso 11-10851

require_relative './lexer/findRegex'
require_relative './parser/racc.rb'

def main
    myfile = File::read(ARGV[0])
    if ARGV.length == 1
        lexer  = FindRegex::new(myfile)
        lexer.findAll

        if lexer.errorFound
            lexer.printOutPut
        else
            tree = Calcparser::Parser.new.parser(lexer.toList)
            #tree.print
            st = tree.get_symbol_table
            st.printTb
            #puts "#{st.inspect}"
            #tree.check
        end

        
    end
end

main