#!/usr/bin/env ruby

# Javier Lopez 11-10552
# Patricia Reinoso 11-10851

require_relative './lexer/findRegex'
require_relative './parser/racc.rb'

def main
    myfile = File::read(ARGV[0])
    if ARGV.length == 1

        # Convertir archivo en tokens
        lexer  = FindRegex::new(myfile)
        lexer.findAll

        if lexer.errorFound
            lexer.printOutPut
        else
            # Crear arbol sintactico
            tree = Calcparser::Parser.new.parser(lexer.toList)

            # Crear tabla de simbolos
            st   = tree.get_symbol_table
            st.printTb
        end

        
    end
end

main