#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.12
# from Racc grammer file "".
#

require 'racc/parser.rb'

require_relative "tokenClasses"

module Calcparser
  class Parser < Racc::Parser

module_eval(<<'...end grammar.rb/module_eval...', 'grammar.rb', 119)
    def parser(tokens)
        @tokens = tokens
        do_parse
    end

    def next_token
        @tokens.shift
    end
...end grammar.rb/module_eval...
##### State transition tables begin ###

racc_action_table = [
    67,    28,    26,    58,     7,     8,     9,    26,    33,    98,
    90,    91,    29,    37,    38,    51,    52,    41,    53,    54,
    55,    59,    56,    57,    63,    64,    65,    66,    36,    42,
    40,    62,    39,    60,    61,    67,    26,    25,    58,    26,
    26,    23,    97,   101,     7,     8,     9,    69,    37,    38,
    51,    52,    41,    53,    54,    55,    59,    56,    57,    63,
    64,    65,    66,    36,    42,    40,    62,    39,    60,    61,
     7,     8,     9,    18,    19,    18,    19,     3,    28,    28,
    28,    34,    93,    70,    37,    38,    32,    71,    41,    29,
    29,    29,    26,    22,     4,     3,    17,   nil,    17,    36,
    42,    40,   nil,    39,    67,   nil,   nil,    58,   nil,   nil,
    20,   nil,    20,   nil,    21,   nil,    21,    37,    38,    51,
    52,    41,    53,    54,    55,    59,    56,    57,    63,    64,
    65,    66,    36,    42,    40,    62,    39,    60,    61,    18,
    19,    18,    19,   nil,    18,    19,   nil,    49,   nil,    18,
    19,   nil,   nil,   nil,    37,    38,   nil,   nil,    41,   nil,
   nil,   nil,    17,   nil,    17,   nil,   nil,    17,   nil,    36,
    42,    40,    17,    39,   nil,   nil,    20,   nil,    20,   nil,
    21,    20,    21,   nil,    67,    21,    20,    58,   nil,   nil,
    21,   nil,   nil,   nil,   nil,   nil,   nil,    37,    38,    51,
    52,    41,    53,    54,    55,    59,    56,    57,    63,    64,
    65,    66,    36,    42,    40,    62,    39,    60,    61,    67,
   nil,    99,    58,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    37,    38,    51,    52,    41,    53,    54,    55,
    59,    56,    57,    63,    64,    65,    66,    36,    42,    40,
    62,    39,    60,    61,    67,   nil,    92,    58,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    37,    38,    51,
    52,    41,    53,    54,    55,    59,    56,    57,    63,    64,
    65,    66,    36,    42,    40,    62,    39,    60,    61,    67,
   nil,   nil,    58,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    37,    38,    51,    52,    41,    53,    54,    55,
    59,    56,    57,    63,    64,    65,    66,    36,    42,    40,
    62,    39,    60,    61,    67,   nil,   nil,    58,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    37,    38,    51,
    52,    41,    53,    54,    55,    59,    56,    57,    63,    64,
    65,    66,    36,    42,    40,    62,    39,    60,    61,    67,
   nil,   nil,    58,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    37,    38,    51,    52,    41,    53,    54,    55,
    59,    56,    57,    63,    64,    65,    66,    36,    42,    40,
    62,    39,    60,    61,    67,   nil,   nil,    58,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    37,    38,    51,
    52,    41,    53,    54,    55,    59,    56,    57,    63,    64,
    65,    66,    36,    42,    40,    62,    39,    60,    61,    67,
   nil,   nil,    58,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    37,    38,    51,    52,    41,    53,    54,    55,
    59,    56,    57,    63,    64,    65,    66,    36,    42,    40,
    62,    39,    60,    61,    67,   nil,   nil,    58,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    37,    38,    51,
    52,    41,    53,    54,    55,    59,    56,    57,    63,    64,
    65,    66,    36,    42,    40,    62,    39,    60,    61,    67,
   nil,   nil,    58,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    37,    38,    51,    52,    41,    53,    54,    55,
    59,    56,    57,    63,    64,    65,    66,    36,    42,    40,
    62,    39,    60,    61,    67,   nil,   nil,    58,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    37,    38,    51,
    52,    41,    53,    54,    55,    59,    56,    57,    63,    64,
    65,    66,    36,    42,    40,    62,    39,    60,    61,    67,
   nil,   nil,    58,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    37,    38,    51,    52,    41,    53,    54,    55,
    59,    56,    57,    63,    64,    65,    66,    36,    42,    40,
    62,    39,    60,    61,    67,   nil,   nil,    58,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    37,    38,    51,
    52,    41,    53,    54,    55,    59,    56,    57,    63,    64,
    65,    66,    36,    42,    40,    62,    39,    60,    61,    67,
   nil,   nil,    58,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    37,    38,    51,    52,    41,    53,    54,    55,
    59,    56,    57,    63,    64,    65,    66,    36,    42,    40,
    62,    39,    60,    61,    67,   nil,   nil,    58,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    37,    38,    51,
    52,    41,    53,    54,    55,    59,    56,    57,    63,    64,
    65,    66,    36,    42,    40,    62,    39,    60,    61,    67,
   nil,   nil,    58,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    37,    38,    51,    52,    41,    53,    54,    55,
    59,    56,    57,    63,    64,    65,    66,    36,    42,    40,
    62,    39,    60,    61,    67,   nil,   nil,    58,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    37,    38,    51,
    52,    41,    53,    54,    55,    59,    56,    57,    63,    64,
    65,    66,    36,    42,    40,    62,    39,    60,    61,    67,
   nil,   nil,    58,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    37,    38,    51,    52,    41,    53,    54,    55,
    59,    56,    57,    63,    64,    65,    66,    36,    42,    40,
    62,    39,    60,    61,    67,   nil,   nil,    58,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    37,    38,    51,
    52,    41,    53,    54,    55,    59,    56,    57,    63,    64,
    65,    66,    36,    42,    40,    62,    39,    60,    61,    67,
   nil,   nil,    58,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    37,    38,    51,    52,    41,    53,    54,    55,
    59,    56,    57,    63,    64,    65,    66,    36,    42,    40,
    62,    39,    60,    61,    37,    38,   nil,   nil,    41,    37,
    38,   nil,   nil,    41,   nil,   nil,   nil,   nil,   nil,    36,
    42,    40,   nil,    39,    36,    42,    40,   nil,    39,   nil,
    44,    37,    38,   nil,   nil,    41,    37,    38,   nil,   nil,
    41,    37,    38,   nil,   nil,    41,    36,    42,    40,   nil,
    39,    36,    42,    40,   nil,    39,    36,    42,    40,   nil,
    39,    37,    38,   nil,   nil,    41,    37,    38,   nil,   nil,
    41,    37,    38,   nil,   nil,    41,    36,    42,    40,   nil,
    39,    36,    42,    40,   nil,    39,    36,    42,    40,   nil,
    39,    37,    38,   nil,   nil,    41,    37,    38,   nil,   nil,
    41,    37,    38,   nil,   nil,    41,    36,    42,    40,   nil,
    39,    36,    42,    40,   nil,    39,    36,    42,    40,   nil,
    39,    37,    38,   nil,   nil,    41,    37,    38,   nil,   nil,
    41,    37,    38,   nil,   nil,    41,    36,    42,    40,   nil,
    39,    36,    42,    40,   nil,    39,    36,    42,    40,   nil,
    39,    37,    38,   nil,   nil,    41,    37,    38,   nil,   nil,
    41,    37,    38,   nil,   nil,    41,    36,    42,    40,   nil,
    39,    36,    42,    40,   nil,    39,    36,    42,    40,   nil,
    39,    37,    38,   nil,   nil,    41,    37,    38,   nil,   nil,
    41,    37,    38,   nil,   nil,    41,    36,    42,    40,   nil,
    39,    36,    42,    40,   nil,    39,    36,    42,    40,   nil,
    39 ]

racc_action_check = [
    43,     9,    95,    43,     5,     5,     5,    72,    18,    95,
    72,    72,     9,    43,    43,    43,    43,    43,    43,    43,
    43,    43,    43,    43,    43,    43,    43,    43,    43,    43,
    43,    43,    43,    43,    43,    89,   100,     6,    89,    94,
     6,     5,    94,   100,    24,    24,    24,    43,    89,    89,
    89,    89,    89,    89,    89,    89,    89,    89,    89,    89,
    89,    89,    89,    89,    89,    89,    89,    89,    89,    89,
     3,     3,     3,    99,    99,     3,     3,    23,     8,    28,
     7,    19,    89,    44,    51,    51,    17,    45,    51,     8,
    28,     7,    46,     4,     1,     0,    99,   nil,     3,    51,
    51,    51,   nil,    51,    35,   nil,   nil,    35,   nil,   nil,
    99,   nil,     3,   nil,    99,   nil,     3,    35,    35,    35,
    35,    35,    35,    35,    35,    35,    35,    35,    35,    35,
    35,    35,    35,    35,    35,    35,    35,    35,    35,    92,
    92,    26,    26,   nil,    49,    49,   nil,    35,   nil,    91,
    91,   nil,   nil,   nil,    56,    56,   nil,   nil,    56,   nil,
   nil,   nil,    92,   nil,    26,   nil,   nil,    49,   nil,    56,
    56,    56,    91,    56,   nil,   nil,    92,   nil,    26,   nil,
    92,    49,    26,   nil,    96,    49,    91,    96,   nil,   nil,
    91,   nil,   nil,   nil,   nil,   nil,   nil,    96,    96,    96,
    96,    96,    96,    96,    96,    96,    96,    96,    96,    96,
    96,    96,    96,    96,    96,    96,    96,    96,    96,    88,
   nil,    96,    88,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    88,    88,    88,    88,    88,    88,    88,    88,
    88,    88,    88,    88,    88,    88,    88,    88,    88,    88,
    88,    88,    88,    88,    82,   nil,    88,    82,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    82,    82,    82,
    82,    82,    82,    82,    82,    82,    82,    82,    82,    82,
    82,    82,    82,    82,    82,    82,    82,    82,    82,    83,
   nil,   nil,    83,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    83,    83,    83,    83,    83,    83,    83,    83,
    83,    83,    83,    83,    83,    83,    83,    83,    83,    83,
    83,    83,    83,    83,    77,   nil,   nil,    77,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    77,    77,    77,
    77,    77,    77,    77,    77,    77,    77,    77,    77,    77,
    77,    77,    77,    77,    77,    77,    77,    77,    77,    76,
   nil,   nil,    76,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    76,    76,    76,    76,    76,    76,    76,    76,
    76,    76,    76,    76,    76,    76,    76,    76,    76,    76,
    76,    76,    76,    76,    78,   nil,   nil,    78,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    78,    78,    78,
    78,    78,    78,    78,    78,    78,    78,    78,    78,    78,
    78,    78,    78,    78,    78,    78,    78,    78,    78,    75,
   nil,   nil,    75,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    75,    75,    75,    75,    75,    75,    75,    75,
    75,    75,    75,    75,    75,    75,    75,    75,    75,    75,
    75,    75,    75,    75,    74,   nil,   nil,    74,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    74,    74,    74,
    74,    74,    74,    74,    74,    74,    74,    74,    74,    74,
    74,    74,    74,    74,    74,    74,    74,    74,    74,    79,
   nil,   nil,    79,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    79,    79,    79,    79,    79,    79,    79,    79,
    79,    79,    79,    79,    79,    79,    79,    79,    79,    79,
    79,    79,    79,    79,    73,   nil,   nil,    73,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    73,    73,    73,
    73,    73,    73,    73,    73,    73,    73,    73,    73,    73,
    73,    73,    73,    73,    73,    73,    73,    73,    73,    80,
   nil,   nil,    80,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    80,    80,    80,    80,    80,    80,    80,    80,
    80,    80,    80,    80,    80,    80,    80,    80,    80,    80,
    80,    80,    80,    80,    68,   nil,   nil,    68,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    68,    68,    68,
    68,    68,    68,    68,    68,    68,    68,    68,    68,    68,
    68,    68,    68,    68,    68,    68,    68,    68,    68,    86,
   nil,   nil,    86,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    86,    86,    86,    86,    86,    86,    86,    86,
    86,    86,    86,    86,    86,    86,    86,    86,    86,    86,
    86,    86,    86,    86,    85,   nil,   nil,    85,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    85,    85,    85,
    85,    85,    85,    85,    85,    85,    85,    85,    85,    85,
    85,    85,    85,    85,    85,    85,    85,    85,    85,    48,
   nil,   nil,    48,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    48,    48,    48,    48,    48,    48,    48,    48,
    48,    48,    48,    48,    48,    48,    48,    48,    48,    48,
    48,    48,    48,    48,    81,   nil,   nil,    81,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    81,    81,    81,
    81,    81,    81,    81,    81,    81,    81,    81,    81,    81,
    81,    81,    81,    81,    81,    81,    81,    81,    81,    50,
   nil,   nil,    50,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    50,    50,    50,    50,    50,    50,    50,    50,
    50,    50,    50,    50,    50,    50,    50,    50,    50,    50,
    50,    50,    50,    50,    84,   nil,   nil,    84,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    84,    84,    84,
    84,    84,    84,    84,    84,    84,    84,    84,    84,    84,
    84,    84,    84,    84,    84,    84,    84,    84,    84,    87,
   nil,   nil,    87,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    87,    87,    87,    87,    87,    87,    87,    87,
    87,    87,    87,    87,    87,    87,    87,    87,    87,    87,
    87,    87,    87,    87,    21,    21,   nil,   nil,    21,    57,
    57,   nil,   nil,    57,   nil,   nil,   nil,   nil,   nil,    21,
    21,    21,   nil,    21,    57,    57,    57,   nil,    57,   nil,
    21,    58,    58,   nil,   nil,    58,    59,    59,   nil,   nil,
    59,    54,    54,   nil,   nil,    54,    58,    58,    58,   nil,
    58,    59,    59,    59,   nil,    59,    54,    54,    54,   nil,
    54,    61,    61,   nil,   nil,    61,    63,    63,   nil,   nil,
    63,    64,    64,   nil,   nil,    64,    61,    61,    61,   nil,
    61,    63,    63,    63,   nil,    63,    64,    64,    64,   nil,
    64,    65,    65,   nil,   nil,    65,    66,    66,   nil,   nil,
    66,    67,    67,   nil,   nil,    67,    65,    65,    65,   nil,
    65,    66,    66,    66,   nil,    66,    67,    67,    67,   nil,
    67,    52,    52,   nil,   nil,    52,    93,    93,   nil,   nil,
    93,    70,    70,   nil,   nil,    70,    52,    52,    52,   nil,
    52,    93,    93,    93,   nil,    93,    70,    70,    70,   nil,
    70,    55,    55,   nil,   nil,    55,    39,    39,   nil,   nil,
    39,    32,    32,   nil,   nil,    32,    55,    55,    55,   nil,
    55,    39,    39,    39,   nil,    39,    32,    32,    32,   nil,
    32,    60,    60,   nil,   nil,    60,    20,    20,   nil,   nil,
    20,    69,    69,   nil,   nil,    69,    60,    60,    60,   nil,
    60,    20,    20,    20,   nil,    20,    69,    69,    69,   nil,
    69 ]

racc_action_pointer = [
    54,    94,   nil,    65,    93,    -1,    -6,    47,    45,   -32,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    41,   -25,    48,
  1048,   866,   nil,    36,    39,   nil,   131,   nil,    46,   nil,
   nil,   nil,  1023,   nil,   nil,    99,   nil,   nil,   nil,  1018,
   nil,   nil,   nil,    -5,    33,    44,    46,   nil,   704,   134,
   774,    66,   983,   nil,   903,  1013,   136,   871,   893,   898,
  1043,   923,   nil,   928,   933,   953,   958,   963,   599,  1053,
   993,   nil,   -39,   529,   459,   424,   354,   319,   389,   494,
   564,   739,   249,   284,   809,   669,   634,   844,   214,    30,
   nil,   139,   129,   988,    -7,   -44,   179,   nil,   nil,    63,
   -10,   nil ]

racc_action_default = [
   -51,   -51,    -1,   -51,   -51,   -51,   -51,   -51,   -51,   -51,
   -11,   -12,   -13,   -14,   -15,   -16,   -17,   -51,   -51,   -51,
   -51,   -51,   102,   -51,    -7,    -3,   -51,    -4,   -51,   -10,
    -5,    -6,   -51,   -20,   -21,   -51,   -26,   -30,   -31,   -51,
   -42,   -43,   -50,   -51,   -51,   -51,   -19,    -9,   -18,   -51,
   -49,   -51,   -51,   -29,   -51,   -51,   -51,   -51,   -51,   -51,
   -51,   -51,   -40,   -51,   -51,   -51,   -51,   -51,   -41,   -51,
   -51,    -2,   -51,   -27,   -28,   -32,   -33,   -34,   -35,   -36,
   -37,   -38,   -39,   -44,   -45,   -46,   -47,   -48,   -51,   -51,
   -22,   -51,   -51,   -51,   -51,   -51,   -51,   -23,   -24,   -51,
   -51,   -25 ]

racc_goto_table = [
     6,     2,     5,     1,   nil,    27,    30,    31,   nil,   nil,
   nil,   nil,   nil,    35,    43,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    46,    45,    48,    47,   nil,   nil,   nil,
   nil,   nil,    68,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    73,    74,    72,    75,    76,    77,
    78,    79,    80,    81,    82,   nil,    83,    84,    85,    86,
    87,   nil,    88,    89,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    96,   nil,    94,    95,
   nil,   nil,   nil,   nil,   nil,   nil,   100 ]

racc_goto_check = [
     4,     2,     3,     1,   nil,     5,     5,     5,   nil,   nil,
   nil,   nil,   nil,    13,    13,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     4,     2,    13,     5,   nil,   nil,   nil,
   nil,   nil,    13,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    13,    13,     4,    13,    13,    13,
    13,    13,    13,    13,    13,   nil,    13,    13,    13,    13,
    13,   nil,    13,    13,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    13,   nil,     4,     4,
   nil,   nil,   nil,   nil,   nil,   nil,     4 ]

racc_goto_pointer = [
   nil,     3,     1,    -1,    -3,    -2,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    -7 ]

racc_goto_default = [
   nil,   nil,   nil,    24,   nil,   nil,    10,    11,    12,    13,
    14,    15,    16,    50 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 55, :_reduce_1,
  5, 56, :_reduce_none,
  3, 56, :_reduce_none,
  2, 57, :_reduce_none,
  2, 57, :_reduce_none,
  2, 57, :_reduce_none,
  2, 57, :_reduce_none,
  1, 57, :_reduce_none,
  2, 59, :_reduce_none,
  1, 59, :_reduce_none,
  1, 58, :_reduce_none,
  1, 58, :_reduce_none,
  1, 58, :_reduce_none,
  1, 58, :_reduce_none,
  1, 58, :_reduce_none,
  1, 58, :_reduce_none,
  1, 58, :_reduce_none,
  3, 60, :_reduce_none,
  3, 61, :_reduce_none,
  2, 62, :_reduce_none,
  2, 63, :_reduce_none,
  5, 64, :_reduce_none,
  7, 64, :_reduce_none,
  7, 65, :_reduce_none,
  9, 66, :_reduce_none,
  1, 67, :_reduce_none,
  3, 67, :_reduce_none,
  3, 67, :_reduce_none,
  2, 67, :_reduce_none,
  1, 67, :_reduce_none,
  1, 67, :_reduce_none,
  3, 67, :_reduce_none,
  3, 67, :_reduce_none,
  3, 67, :_reduce_none,
  3, 67, :_reduce_none,
  3, 67, :_reduce_none,
  3, 67, :_reduce_none,
  3, 67, :_reduce_none,
  3, 67, :_reduce_none,
  2, 67, :_reduce_none,
  2, 67, :_reduce_none,
  1, 67, :_reduce_none,
  1, 67, :_reduce_none,
  3, 67, :_reduce_none,
  3, 67, :_reduce_none,
  3, 67, :_reduce_none,
  3, 67, :_reduce_none,
  3, 67, :_reduce_none,
  2, 67, :_reduce_none,
  1, 67, :_reduce_none ]

racc_reduce_n = 51

racc_shift_n = 102

racc_token_table = {
  false => 0,
  :error => 1,
  "LCURLY" => 2,
  "RCURLY" => 3,
  "PIPE" => 4,
  "PERCENT" => 5,
  "EXCLAMATIONMARK" => 6,
  "AT" => 7,
  "EQUALS" => 8,
  "SEMICOLON" => 9,
  "READ" => 10,
  "WRITE" => 11,
  "QUESTIONMARK" => 12,
  "COLON" => 13,
  "LSQUARE" => 14,
  "RSQUARE" => 15,
  "LPARENTHESIS" => 16,
  "RPARENTHESIS" => 17,
  "TRUE" => 18,
  "FALSE" => 19,
  "AND" => 20,
  "OR" => 21,
  "CANVAS" => 22,
  "NOT" => 23,
  "LESSTHAN" => 24,
  "MORETHAN" => 25,
  "NOTEQUALS" => 26,
  "LESS" => 27,
  "MORE" => 28,
  "PLUS" => 29,
  "MINUS" => 30,
  "MULTIPLICATION SIGN" => 31,
  "SLASH" => 32,
  "IDENTIFIER" => 33,
  "NUMBER" => 34,
  "EMPTY CANVAS" => 35,
  "TRANSPOSE" => 36,
  "ROTATION" => 37,
  "HORIZONTAL CONCAT" => 38,
  "VERTICAL CONCAT" => 39,
  "COMPREHENSION" => 40,
  "{" => 41,
  "|" => 42,
  "}" => 43,
  :identifier => 44,
  "=" => 45,
  ";" => 46,
  "(" => 47,
  "?" => 48,
  ")" => 49,
  ":" => 50,
  "[" => 51,
  ".." => 52,
  "]" => 53 }

racc_nt_base = 54

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "LCURLY",
  "RCURLY",
  "PIPE",
  "PERCENT",
  "EXCLAMATIONMARK",
  "AT",
  "EQUALS",
  "SEMICOLON",
  "READ",
  "WRITE",
  "QUESTIONMARK",
  "COLON",
  "LSQUARE",
  "RSQUARE",
  "LPARENTHESIS",
  "RPARENTHESIS",
  "TRUE",
  "FALSE",
  "AND",
  "OR",
  "CANVAS",
  "NOT",
  "LESSTHAN",
  "MORETHAN",
  "NOTEQUALS",
  "LESS",
  "MORE",
  "PLUS",
  "MINUS",
  "MULTIPLY",
  "SLASH",
  "IDENTIFIER",
  "NUMBER",
  "EMPTYCANVAS",
  "TRANSPOSE",
  "ROTATION",
  "HORIZONTALCAT",
  "VERTICALCAT",
  "COMPREHENSION",
  "\"{\"",
  "\"|\"",
  "\"}\"",
  "identifier",
  "\"=\"",
  "\";\"",
  "\"(\"",
  "\"?\"",
  "\")\"",
  "\":\"",
  "\"[\"",
  "\"..\"",
  "\"]\"",
  "$start",
  "target",
  "program",
  "declare",
  "instruction",
  "identifierlist",
  "assigment",
  "sequence",
  "input",
  "output",
  "conditional",
  "notDetIteration",
  "detIteration",
  "exp" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'grammar.rb', 46)
  def _reduce_1(val, _values, result)
    puts "#{val}"
    result
  end
.,.,

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Calcparser
