#!/usr/bin/env ruby

# Javier Lopez 11-10552
# Patricia Reinoso 11-10851

require_relative 'findRegex'

def main
	myfile = File::read(ARGV[0])
	puts myfile
	if ARGV.length == 1
		lexer = FindRegex::new(myfile)
		lexer.findAll
		lexer.printOutPut
	end
end

main