#!/usr/bin/env ruby

# Javier Lopez 11-10552
# Patricia Reinoso 11-10851

require_relative 'findRegex'

def main
	myfile = File::read(ARGV[0])
	puts myfile
	lexer = FindRegex::new(myfile)
	lexer.findAll
	lexer.printOutPut
end

main